namespace Prg_Moadian.SQLMODELS
{
    public class SAZMAN
    {
        public double? UNIVERSITY_CO { get; set; }
        public string NAME { get; set; }
        public string CITY { get; set; }
        public string MANAGER { get; set; }
        public string MOAVEN { get; set; }
        public string ZIHESAB { get; set; }
        public string AMINAMVAL { get; set; }
        public short? YEA { get; set; }
        public short? SANAD { get; set; }
        public short? GHAYM { get; set; }
        public short? KALA { get; set; }
        public short? PERSON { get; set; }
        public double? DIG { get; set; }
        public double? WAR { get; set; }
        public double? LST { get; set; }
        public double? TFTPAGE { get; set; }
        public string TFSAZMAN { get; set; }
        public string TFADDRESS { get; set; }
        public string TFTEL { get; set; }
        public string TFCODE_E { get; set; }
        public string WIDTH_D { get; set; }
        public string HIGH_D { get; set; }
        public double? CPI { get; set; }
        public double? SANDOGH { get; set; }
        public double? BANKHA { get; set; }
        public double? BESTANKAR { get; set; }
        public double? BEDEHKAR { get; set; }
        public double? KHARID { get; set; }
        public double? MKHARID { get; set; }
        public double? TKHARID { get; set; }
        public double? HKHARID { get; set; }
        public double? FROSH { get; set; }
        public double? MFROSH { get; set; }
        public double? TFROSH { get; set; }
        public double? HFROSH { get; set; }
        public double? MOGODIA { get; set; }
        public double? MOGODIP { get; set; }
        public double? DARAM { get; set; }
        public double? HDARAM { get; set; }
        public double? HKOL { get; set; }
        public string ADA { get; set; }
        public string APA { get; set; }
        public string ADV { get; set; }
        public double? HAVALAH { get; set; }
        public double? CTRL_TS { get; set; }
        public double? F_ANBARF { get; set; }
        public double? GH_PK { get; set; }
        public double? L_NUMBER { get; set; }
        public double? SF_G { get; set; }
        public double? TAR_KM { get; set; }
        public string BACKPATH { get; set; }
        public int? TKHF { get; set; }
        public double? HAZ_TOL { get; set; }
        public double? PJHAZ_TOL1 { get; set; }
        public double? PHAZ_TOL { get; set; }
        public double? GHEYMAT { get; set; }
        public double? PPDAST { get; set; }
        public double? PPSAR { get; set; }
        public double? AMALKARD { get; set; }
        public string PERSONEL { get; set; }
        public string PERVAM { get; set; }
        public double? CONKAL { get; set; }
        public byte[] EMZA { get; set; }
        public bool? HNAH { get; set; }
        public bool? HEZA { get; set; }
        public bool? HPAD { get; set; }
        public bool? HOLA { get; set; }
        public bool? HKHA { get; set; }
        public bool? HJAZ { get; set; }
        public bool? HRAN { get; set; }
        public bool? HSAY { get; set; }
        public bool? HCON { get; set; }
        public bool? HSHI { get; set; }
        public string HAZEDAR { get; set; }
        public string EDABIM { get; set; }
        public string HAZBIM { get; set; }
        public string BESHO { get; set; }
        public string BEDMOS { get; set; }
        public string PARDAKH { get; set; }
        public string HAZMALI { get; set; }
        public int? SAGHFH { get; set; }
        public bool? MAND { get; set; }
        public bool? MOJU { get; set; }
        public bool? SA_HOGH { get; set; }
        public bool? SA_40EZ { get; set; }
        public bool? SA_EZAF { get; set; }
        public bool? SA_PADA { get; set; }
        public bool? SA_HOLA { get; set; }
        public bool? SA_KHAR { get; set; }
        public bool? SA_NAHA { get; set; }
        public bool? SA_JAZB { get; set; }
        public bool? SA_RAND { get; set; }
        public bool? SA_COND { get; set; }
        public bool? SA_SAYE { get; set; }
        public bool? SA_23BI { get; set; }
        public string HAZTOLID { get; set; }
        public string HAZFROOSH { get; set; }
        public string HAZKHADAMAT { get; set; }
        public double? PISHDAR { get; set; }
        public short? DEFANB { get; set; }
        public short? DEFTKH { get; set; }
        public bool? ECONM { get; set; }
        public bool? FRUP { get; set; }
        public bool? UPDDATE { get; set; }
        public bool? FINALS { get; set; }
        public string PSANDHES { get; set; }
        public int? SANAVP { get; set; }
        public int? BON { get; set; }
        public string ISO_FROOSH { get; set; }
        public string ISO_KHAREED { get; set; }
        public string ISO_MAVAD { get; set; }
        public string ISO_TOLID { get; set; }
        public string ISO_MAVADSAYER { get; set; }
        public bool? SANAT { get; set; }
        public short? CODEVIEW { get; set; }
        public int? PKHARID { get; set; }
        public bool? SIGN { get; set; }
        public bool? BARCOD { get; set; }
        public bool? SAGHF { get; set; }
        public string SERVERNAM { get; set; }
        public bool? TENDAR { get; set; }
        public string LECOL1 { get; set; }
        public string LECOL2 { get; set; }
        public string LECOL3 { get; set; }
        public string LECOL4 { get; set; }
        public string LKCOL1 { get; set; }
        public string HESMBAA { get; set; }
        public string ECODE { get; set; }
        public string PCODE { get; set; }
        public string IYALAT { get; set; }
        public string MCODEM { get; set; }
        public string HPOR { get; set; }
        public bool? SAGHF2 { get; set; }
        public string OPTIONSS { get; set; }
        public bool? CTL_DT { get; set; }
        public bool? LOCKFAP { get; set; }
        public bool? LOCKFSI { get; set; }
        public bool? TRANSF { get; set; }
        public bool? OKF { get; set; }
        public byte ARSESH { get; set; }
        public bool? RMOG { get; set; }
        public string APV { get; set; }
        public string HOTCOD { get; set; }
        public int? STFR { get; set; }
        public int? STKH { get; set; }
        public int? STHFR { get; set; }
        public int? STHKH { get; set; }
        public int? STENT { get; set; }
        public int? STKHS { get; set; }
        public int? STKHH { get; set; }
        public int? STTOL { get; set; }
        public int? STFRB { get; set; }
        public int? STBKH { get; set; }
        public int? STMO { get; set; }
        public int? STKHA { get; set; }
        public bool? SNDKH { get; set; }
        public string SMS_USERNAME { get; set; }
        public string SMS_PASSWORD { get; set; }
        public string SMS_LIBKEY { get; set; }
        public string SMS_TSMSHOST { get; set; }
        public string SMS_ProxyUserName { get; set; }
        public string SMS_ProxyPassword { get; set; }
        public string SMS_ProxyServer { get; set; }
        public string SMS_ProxyPort { get; set; }
        public string SMS_FirewallUserName { get; set; }
        public string SMS_FirewallPassword { get; set; }
        public string SMS_FirewallHost { get; set; }
        public string SMS_FirewallPort { get; set; }
        public string SMS_FirewallType { get; set; }
        public bool? DSMS { get; set; }
        public string SMS_OWNER { get; set; }
        public bool? PRMFR { get; set; }
        public bool? SMSACT { get; set; }
        public string HESDESK { get; set; }
        public string ISO_DTOLID { get; set; }
        public bool? SERFACB { get; set; }
        public bool? HBON { get; set; }
        public int? pishpross { get; set; }
        public string version { get; set; }
        public string hesnaghd { get; set; }
        public string IT1 { get; set; }
        public string IT2 { get; set; }
        public string IT3 { get; set; }
        public string IT4 { get; set; }
        public string IT5 { get; set; }
        public string IT6 { get; set; }
        public string IT7 { get; set; }
        public string IT8 { get; set; }
        public string IT9 { get; set; }
        public string IS1 { get; set; }
        public string IS2 { get; set; }
        public string IS3 { get; set; }
        public string IS4 { get; set; }
        public string IS5 { get; set; }
        public string IS6 { get; set; }
        public string IS7 { get; set; }
        public string IS8 { get; set; }
        public string IS9 { get; set; }
        public string IS10 { get; set; }
        public string IS11 { get; set; }
        public string IS12 { get; set; }
        public string IS13 { get; set; }
        public string IS14 { get; set; }
        public string IS15 { get; set; }
        public string IS16 { get; set; }
        public int? SSMTRTAKM { get; set; }
        public int? SSMTRTAGM { get; set; }
        public int? SSMSNDAUTO { get; set; }
        public int? SSMTBMON { get; set; }
        public Single? SSMDARSAD { get; set; }
        public string HDARKASRTAKHF { get; set; }
        public DateTime? CRT { get; set; }
        public int? UID { get; set; }
        public string PRIVIATEKEY { get; set; }
        public string MEMORYID { get; set; }
        public string MEMORYIDsand { get; set; }
        public string Dcertificate { get; set; }
        /// <summary>
        /// Inno شماره شروع فاکتور از سال قبل
        /// </summary>
        public decimal MOADINA_SCNUM { get; set; }
    }
}
