namespace Prg_Moadian.SQLMODELS
{
    public class TAXDTL
    {
        public string? Taxid { get; set; }
        public string? REMARKS { get; set; }
        public Int64? Indatim { get; set; }
        public Int64? Indati2m { get; set; }
        public int? Inty { get; set; }
        public string? Inno { get; set; }
        public string? Irtaxid { get; set; }
        public int? Inp { get; set; }
        public int? Ins { get; set; }
        public string? Tins { get; set; }
        public int? Tob { get; set; }
        public string? Bid { get; set; }
        public string? Tinb { get; set; }
        public string? Sbc { get; set; }
        public string? Bbc { get; set; }
        public string? Bpc { get; set; }
        public int? Ft { get; set; }
        public string? Bpn { get; set; }
        public string? Scln { get; set; }
        public string? Scc { get; set; }
        public string? Crn { get; set; }
        public string? Billid { get; set; }
        public decimal? Tprdis { get; set; }
        public decimal? Tdis { get; set; }
        public decimal? Tadis { get; set; }
        public decimal? Tvam { get; set; }
        public decimal? Todam { get; set; }
        public decimal? Tbill { get; set; }
        public decimal? Setm { get; set; }
        public decimal? Cap { get; set; }
        public decimal? Insp { get; set; }
        public decimal? Tvop { get; set; }
        public decimal? Tax17 { get; set; }
        public string? Sstid { get; set; }
        public string? Sstt { get; set; }
        public string? Mu { get; set; }
        public decimal? Am { get; set; }
        public decimal? Fee { get; set; }
        public decimal? Cfee { get; set; }
        public string? Cut { get; set; }
        public decimal? Exr { get; set; }
        public decimal? Prdis { get; set; }
        public decimal? Dis { get; set; }
        public decimal? Adis { get; set; }
        public decimal? Vra { get; set; }
        public decimal? Vam { get; set; }
        public string? Odt { get; set; }
        public decimal? Odr { get; set; }
        public decimal? Odam { get; set; }
        public string? Olt { get; set; }
        public decimal? Olr { get; set; }
        public decimal? Olam { get; set; }
        public decimal? Consfee { get; set; }
        public decimal? Spro { get; set; }
        public decimal? Bros { get; set; }
        public decimal? Tcpbs { get; set; }
        public decimal? Cop { get; set; }
        public decimal? Vop { get; set; }
        public string? Bsrn { get; set; }
        public decimal? Tsstam { get; set; }
        public string? Iinn { get; set; }
        public string? Acn { get; set; }
        public string? Trmn { get; set; }
        public string? Trn { get; set; }
        public string? Pcn { get; set; }
        public string? Pid { get; set; }
        public decimal? Pdt { get; set; }
        public string? Cdcn { get; set; }
        public int? Cdcd { get; set; }
        public decimal? Tonw { get; set; }
        public decimal? Torv { get; set; }
        public decimal? Tocv { get; set; }
        public decimal? Nw { get; set; }
        public decimal? Ssrv { get; set; }
        public decimal? Sscv { get; set; }
        public int? Pmt { get; set; }
        public decimal? PV { get; set; }
        public int? IDD { get; set; }
        public DateTime? CRT { get; set; }
        public string? UID { get; set; }
        public string? RefrenceNumber { get; set; }
        public string? TheConfirmationReferenceId { get; set; }
        public string? TheError { get; set; }
        public string? TheStatus { get; set; }
        public bool? TheSuccess { get; set; }
        public string? TheWarning { get; set; }

        public Int64? Indatim_Sec { get; set; }
        public Int64? Indati2m_Sec { get; set; }

        public double? NUMBER { get; set; }
        public double? TAG { get; set; }
        public int? DATE_N { get; set; }
    }
}
